# Generated by Django 3.0.7 on 2020-08-27 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', 'init_records'),
        ('accounts', '0002_auto_20200827_1113'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserRecords',
            new_name='UserRecord',
        ),
    ]
