# Generated by Django 3.1 on 2020-08-30 03:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('records', '0001_recordstatus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecordStatus',
            new_name='CheckedRecord',
        ),
    ]
