# Generated by Django 3.0.7 on 2020-08-05 16:12

from django.db import migrations

from records.models import Record, Classification, PSCEDClassification


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    def insertData(app, schema_editor):
        Classification.objects.bulk_create([
            Classification(name='Applied Research'),
            Classification(name='Basic Research'),
        ])

        PSCEDClassification.objects.bulk_create([
            PSCEDClassification(name='Home Economics'),
            PSCEDClassification(name='Architecture and Town Planning'),
            PSCEDClassification(name='Agriculture, Forestry and Fisheries'),
            PSCEDClassification(name='Business Administration and Related'),
            PSCEDClassification(name='Education Science and Teacher Training'),
            PSCEDClassification(name='Engineering and Technology'),
            PSCEDClassification(name='Fine and Applied Arts'),
            PSCEDClassification(name='Humanities'),
            PSCEDClassification(name='Law and Jurisprudence'),
            PSCEDClassification(name='Mass Communication and Documentation'),
            PSCEDClassification(name='Mathematics'),
            PSCEDClassification(name='Medical and Allied'),
            PSCEDClassification(name='Natural Science'),
            PSCEDClassification(name='Religion and Theology'),
            PSCEDClassification(name='Service Trades'),
            PSCEDClassification(name='Social and Behavioral Sciences'),
            PSCEDClassification(name='Trade, Craft and Industrial'),
            PSCEDClassification(name='Other Disciplines'),
            PSCEDClassification(name='IT Related Disciplines'),
        ])

    operations = [
        migrations.RunPython(insertData)
    ]
