# Generated by Django 3.0.7 on 2020-08-06 08:33

from django.db import migrations


def insert_data(apps, schema_editor):
    Classification = apps.get_model('records', 'Classification')
    PSCEDClassification = apps.get_model('records', 'PSCEDClassification')
    CollaborationType = apps.get_model('records', 'CollaborationType')
    BudgetType = apps.get_model('records', 'BudgetType')
    ConferenceLevel = apps.get_model('records', 'ConferenceLevel')
    AuthorRole = apps.get_model('records', 'AuthorRole')
    PublicationLevel = apps.get_model('records', 'PublicationLevel')

    Classification.objects.bulk_create([
        Classification(name='Applied Research'),
        Classification(name='Basic Research'),
    ])

    BudgetType.objects.bulk_create([
        BudgetType(name='School'),
        BudgetType(name='Local'),
        BudgetType(name='Foreign'),
    ])

    ConferenceLevel.objects.bulk_create([
        ConferenceLevel(name='Regional'),
        ConferenceLevel(name='Local'),
        ConferenceLevel(name='National'),
        ConferenceLevel(name='International'),
    ])

    AuthorRole.objects.bulk_create([
        AuthorRole(name='Researcher'),
        AuthorRole(name='Adviser'),
        AuthorRole(name='Presenter'),
    ])

    CollaborationType.objects.bulk_create([
        CollaborationType(name="Academy"),
        CollaborationType(name="Government"),
        CollaborationType(name="Industry"),
    ])

    PSCEDClassification.objects.bulk_create([
        PSCEDClassification(name='Home Economics'),
        PSCEDClassification(name='Architecture and Town Planning'),
        PSCEDClassification(name='Agriculture, Forestry and Fisheries'),
        PSCEDClassification(name='Business Administration and Related'),
        PSCEDClassification(name='Education Science and Teacher Training'),
        PSCEDClassification(name='Engineering and Technology'),
        PSCEDClassification(name='Fine and Applied Arts'),
        PSCEDClassification(name='Humanities'),
        PSCEDClassification(name='Law and Jurisprudence'),
        PSCEDClassification(name='Mass Communication and Documentation'),
        PSCEDClassification(name='Mathematics'),
        PSCEDClassification(name='Medical and Allied'),
        PSCEDClassification(name='Natural Science'),
        PSCEDClassification(name='Religion and Theology'),
        PSCEDClassification(name='Service Trades'),
        PSCEDClassification(name='Social and Behavioral Sciences'),
        PSCEDClassification(name='Trade, Craft and Industrial'),
        PSCEDClassification(name='Other Disciplines'),
        PSCEDClassification(name='IT Related Disciplines'),
    ])

    PublicationLevel.objects.bulk_create([
        PublicationLevel(name='Local'),
        PublicationLevel(name='School'),
        PublicationLevel(name='National'),
        PublicationLevel(name='International'),
    ])


def delete_data(apps, schema_editor):
    Classification = apps.get_model('records', 'Classification')
    PSCEDClassification = apps.get_model('records', 'PSCEDClassification')
    CollaborationType = apps.get_model('records', 'CollaborationType')
    BudgetType = apps.get_model('records', 'BudgetType')
    ConferenceLevel = apps.get_model('records', 'ConferenceLevel')
    AuthorRole = apps.get_model('records', 'AuthorRole')
    PublicationLevel = apps.get_model('records', 'PublicationLevel')

    Classification.objects.all().delete()
    PSCEDClassification.objects.all().delete()
    CollaborationType.objects.all().delete()
    BudgetType.objects.all().delete()
    ConferenceLevel.objects.all().delete()
    AuthorRole.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_data, delete_data)
    ]
