# Generated by Django 3.0.7 on 2020-08-06 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_auto_20200806_1633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='published_level',
            new_name='publication_level',
        ),
    ]
