# Generated by Django 3.0.7 on 2020-08-08 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_auto_20200806_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pscedclassification',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
