# Generated by Django 3.0.7 on 2020-08-08 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_auto_20200808_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='authorrole',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='budget',
            name='funding_source',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='budgettype',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='classification',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='collaboration',
            name='industry',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='collaboration',
            name='institution',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='collaborationtype',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='conference',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='conference',
            name='venue',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='conferencelevel',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pscedclassification',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='publication',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='publicationlevel',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='record',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
