# Generated by Django 3.0.7 on 2020-08-08 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_auto_20200808_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
