# Generated by Django 3.0.7 on 2020-08-12 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0008_auto_20200812_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorrole',
            name='name',
            field=models.CharField(choices=[('researcher', 'Researcher'), ('adviser', 'Adviser'), ('presenter', 'Presenter')], default='presenter', max_length=100),
        ),
    ]
