# Generated by Django 3.0.7 on 2020-08-12 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0009_auto_20200812_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationlevel',
            name='name',
            field=models.CharField(choices=[('local', 'Local'), ('school', 'School'), ('national', 'National')], max_length=100),
        ),
    ]
