# Generated by Django 3.0.7 on 2020-08-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0010_auto_20200812_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorrole',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='publicationlevel',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
