# Generated by Django 3.0.7 on 2020-08-15 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0011_auto_20200812_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.Record'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.Record'),
        ),
        migrations.AlterField(
            model_name='collaboration',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.Record'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.Record'),
        ),
    ]
