# Generated by Django 3.0.7 on 2020-08-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0012_auto_20200815_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='abstract_filename',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
