# Generated by Django 3.0.7 on 2020-08-23 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0013_record_abstract_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='abstract_file',
            field=models.FileField(blank=True, null=True, upload_to='media/abstract/'),
        ),
    ]
