# Generated by Django 3.1 on 2020-08-23 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0015_auto_20200823_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='abstract_filename',
        ),
    ]
